### ISSUE TITLE
Control Strategy Manager - Confirm Deletion

### ISSUE THREAD

**Issue by lizadams** [lizadams/emf#21]
This has a pop-up window that isn't described in the documentation.
For the selected stragegy, which output datasets should be removed?
[] Stragegy results, messages, and summaries
[] Controlled inventories
Then click on the OK or Cancel button
![control_strategy_manager_delete](https://user-images.githubusercontent.com/1183863/28638820-13e986f8-7214-11e7-853c-c9d44820ca62.png)

I am not sure what the user should be selecting.

**Comment by cseppan** [comment]
The option to delete output datasets when deleting a control strategy was added in EMF v2.8, and hasn't been documented. When a control strategy is run, it creates various datasets, like the strategy results and various reports. Users can also choose to create a controlled inventory based on a strategy's results. When deleting a control strategy, the choice of what to do with these outputs is up to the user. Most likely, there's no need to keep the strategy results, etc. if the entire strategy is being deleted. For the User's Guide, both boxes can be checked so that all datasets created by the control strategy are cleaned up when the strategy itself is deleted.

**Comment by lizadams** [comment]
Need to add a screenshot of the Confirm Strategy Deletion menu.
